### PR TITLE
SideNavbar Bug Fixed

### PR DESCRIPTION
**Pull request by B1TSH3LL**
I Have Fixed The SideNavbar bug You Can Check It. Have Fun And Dont Forget To Add Label hactober accepted to count participation at the time of merge 💯

### CODE REVIEW

**Comment by wasim7raja10** [comment]
@B1TSH3LL when I hover over the link, the icon doesn't get highlighted. check the gif.
ui hover

**Comment by wasim7raja10** [comment]
@B1TSH3L
Screenshot from 2021-10-02 19-00-10
The footer is not responsive. Make it responsive.

**Comment by B1TSH3LL** [comment]
Okk I'll Check

**Comment by B1TSH3LL** [comment]
bro i made the changes please check it and merge it. Exciting Project :)

**Comment by wasim7raja10** [comment]
> bro i made the changes please check it and merge it. Exciting Project :)

Awesome, I will check and get back to you.

**Review by wasim7raja10 — CHANGES_REQUESTED** [review]
There are conflicts on your branch. I request you to resolve the merge conflicts. update your local repo and commit again.

**Pull request closed without merging**
