### PR TITLE
i have added footer with github icon and linked it to your repo

### PR DESCRIPTION
**Pull request by harshitsuthar77731**

### CODE REVIEW

**Comment by wasim7raja10** [comment]
@harshitsuthar77731 
The footer is not responsive. Make it responsive.
Screenshot from 2021-10-02 19-00-10

**Comment by harshitsuthar77731** [comment]
okay

**Comment by wasim7raja10** [comment]
> okay

@harshitsuthar77731 also reduce its height a little bit

**Comment by harshitsuthar77731** [comment]
check this udated one

**Comment by harshitsuthar77731** [comment]
updated height by reducing it little bit

**Comment by harshitsuthar77731** [comment]
i have updated all the thing as per requirement and at time of merge don't forget to add hactober fest tag happy coding

**Comment by wasim7raja10** [comment]
@harshitsuthar77731 have you tested in mobile screen ?

**Comment by harshitsuthar77731** [comment]
yes

**Comment by harshitsuthar77731** [comment]
is there any issue

**Comment by harshitsuthar77731** [comment]
Screenshot (50)

**Comment by wasim7raja10** [comment]
> 
> Screenshot (50)
> 
> 

Great I will look into it and get back to you.

**Comment by harshitsuthar77731** [comment]
thank you

**Comment by OfficialSaurabh** [comment]
@harshitsuthar77731 is still not responsive properly, when the left side navbar opens footer not moves to the right.

**Comment by harshitsuthar77731** [comment]
okay i see about this issue

**Comment by harshitsuthar77731** [comment]
i got the issue i will updated the repo tommorrow

**Comment by OfficialSaurabh** [comment]
OK

**Comment by harshitsuthar77731** [comment]
Screenshot (51)
Screenshot (52)
Screenshot (53)
Screenshot (50)


updated the code please guide we if there any issue

**Comment by wasim7raja10** [comment]
@harshitsuthar77731 when there's some content on the page it doesn't stick to the bottom. Also, the code quality is poor. There's lots of inline CSS.  This can be easily done with flexbox or Bootstrap and for sticking it to the bottom you can use the position property for the footer section. I would recommend you to google how to make a footer.

**Comment by harshitsuthar77731** [comment]
okay i would like to improve my code

**Comment by harshitsuthar77731** [comment]
updated the code

**Comment by harshitsuthar77731** [comment]
guide me to improve it further

**Comment by OfficialSaurabh** [comment]
@harshitsuthar77731 someone else has fixed the issue, you can see their code and improve your skills.

**Comment by harshitsuthar77731** [comment]
okay

**Pull request closed without merging**
