### PR TITLE
SideNavbar Hover Fixed

### PR DESCRIPTION
**Pull request by B1TSH3LL**
Hello I Made It Hope You Like It :) 👍🏻

### CODE REVIEW

**Comment by B1TSH3LL** [comment]
please make sure to add hacktoberfest-accepted label

**Comment by B1TSH3LL** [comment]
there were many conflicts so i deleted previous PR and made new one :)

**Review by wasim7raja10 — APPROVED** [review]
You have finally fixed the issue. Thanks for contributing

**Comment by B1TSH3LL** [comment]
bruh can you add hacktoberfest-accepted label for counting my contribution

**Comment by wasim7raja10** [comment]
> bruh can you add hacktoberfest-accepted label for counting my contribution 
> 

@B1TSH3LL don't worry. It will sure be counted. The PR needs to be either merged or labelled Hacktoberfest. Anyway I will label it for your peace of mind.

**Comment by B1TSH3LL** [comment]
Thank You So Much 😊

**Pull request merged**
